window.portfolioData = {
  caseStudies: [
    {
      id: 'medicare-app-redesign',
      number: '01',
      label: 'Case Study',
      title: 'MEDICARE APP REDESIGN',
      description: 'No SIM Swaps. No Local Plans. No Roaming headaches.<br>Just download the app and add your countries on the go.',
      image: 'Banner.png',
      imageAlt: 'Preview of the Medicare app redesign case study',
      buttonText: 'VIEW CASE STUDY',
      buttonHref: '#',
      theme: 'default',
    },
    {
      id: 'telehealth-platform',
      number: '02',
      label: 'Case Study',
      title: 'TELEHEALTH PLATFORM',
      description: 'Helping clinics deliver remote care with an intuitive scheduling and triage experience.<br>Designed to scale from pilot to national rollout.',
      image: 'Banner.png',
      imageAlt: 'Preview of the Telehealth platform case study',
      buttonText: 'VIEW CASE STUDY',
      buttonHref: '#',
      theme: 'indigo',
    },
    {
      id: 'wellness-insights',
      number: '03',
      label: 'Case Study',
      title: 'WELLNESS INSIGHTS DASHBOARD',
      description: 'Turning complex wellness metrics into actionable insights for care teams.<br>Improved adherence and reduced support workloads.',
      image: 'Mockup.png',
      imageAlt: 'Preview of the Wellness insights dashboard case study',
      buttonText: 'VIEW CASE STUDY',
      buttonHref: '#',
      theme: 'carbon',
    },
  ],
  testimonials: [
    {
      id: 'stijn-kra',
      author: 'Stijn Kra',
      role: 'Product Lead, RoamFree',
      date: '2025-05-15T09:31:00Z',
      headline: 'Top eSIM App',
      body: 'This app gives you fast and easy access to the internet worldwide. Their customer support is also excellent. Definitely recommended!',
      rating: 5,
    },
    {
      id: 'maria-fernandez',
      author: 'María Fernández',
      role: 'CEO, SaludNow',
      date: '2024-11-02T14:10:00Z',
      headline: 'A Partner For Growth',
      body: 'Abir helped us simplify a complex onboarding journey into a flow that our users now rave about. The collaboration was smooth and deeply insightful.',
      rating: 5,
    },
    {
      id: 'liam-chan',
      author: 'Liam Chan',
      role: 'Founder, PulseTrack',
      date: '2024-08-21T08:45:00Z',
      headline: 'Intuitive End-To-End Experience',
      body: 'We went from scattered ideas to a polished product vision. The strategy, research, and UI execution landed us our next round of funding.',
      rating: 5,
    },

    {
      id: 'liam-chan',
      author: 'Liam Chan',
      role: 'Founder, PulseTrack',
      date: '2024-08-21T08:45:00Z',
      headline: 'Intuitive End-To-End Experience',
      body: 'We went from scattered ideas to a polished product vision. The strategy, research, and UI execution landed us our next round of funding.',
      rating: 5,
    },
  ],
  faqs: [
    {
      id: 'design-process',
      question: 'What is included in your design process?',
      answer: 'My process includes research, wireframing, visual design, prototyping, and usability testing — all tailored to your product goals.',
      open: true,
    },
    {
      id: 'startups',
      question: 'Do you work with startups?',
      answer: 'Absolutely — I help early-stage teams move from concept to MVP with strong UX foundations and fast, iterative delivery.',
      open: false,
    },
    {
      id: 'redesigns',
      question: 'Can you redesign existing apps?',
      answer: 'Yes. I run UX audits to identify usability issues, then redesign critical flows to lift engagement, retention, and conversion.',
      open: false,
    },
    {
      id: 'redesigns',
      question: 'Can you redesign existing apps?',
      answer: 'Yes. I run UX audits to identify usability issues, then redesign critical flows to lift engagement, retention, and conversion.',
      open: false,
    },
  ],
};
