window.portfolioData = {
  caseStudies: [
    {
      id: 'medicare-app-redesign',
      number: '01',
      label: 'Case Study',
      title: 'MEDICARE APP REDESIGN',
      description: 'No SIM Swaps. No Local Plans. No Roaming headaches.<br>Just download the app and add your countries on the go.',
      image: 'Banner.webp',
      imageAlt: 'Preview of the Medicare app redesign case study',
      buttonText: 'READ CASE STUDY',
      buttonHref: 'https://medium.com/design-bootcamp/the-ux-of-medical-app-how-i-mixup-ai-with-industry-standards-1b7e787c3b9b',
      theme: 'default',
    },
    {
      id: 'dbfex-product-audit-and-redesign',
      number: '02',
      label: 'Product',
      title: 'DBFEX PRODUCT AUDIT AND REDESIGN',
      description: 'Helping clinics deliver remote care with an intuitive scheduling and triage experience.<br>Designed to scale from pilot to national rollout.',
      image: 'cade study 2.webp',
      imageAlt: 'Preview of the Telehealth platform case study',
      buttonText: 'VISIT WEBSITE',
      buttonHref: 'https://dbfex.com/',
      theme: 'indigo',
    },
    {
      id: 'wellness-insights',
      number: '03',
      label: 'UI Design',
      title: 'Travel website UI/UX design',
      description: 'Turning complex wellness metrics into actionable insights for care teams.<br>Improved adherence and reduced support workloads.',
      image: 'Case Study 3.webp',
      imageAlt: 'Preview of the Wellness insights dashboard case study',
      buttonText: 'Presentation',
      buttonHref: 'https://dribbble.com/shots/26499183-Travel-website-UI-UX-design-Responsive',
      theme: 'carbon',
    },
  ],
  testimonials: [
    {
      id: 'stijn-kra',
      author: 'Stijn Kra',
      role: 'CEO, Framify',
      date: '2025-05-15T09:31:00Z',
      logo: 'Framify.svg',
      logoAlt: 'Framify logo',
      headline: 'Abir is a great designer',
      body: 'Talented, reliable, and creative—Abir makes every project look amazing!',
      rating: 5,
      theme: 'onyx',
    },
    {
      id: 'maria-fernandez',
      author: 'María Fernández',
      role: '- Founder, Hilfal Digital',
      date: '2024-11-02T14:10:00Z',
      logo: 'Hilfal digital.svg',
      logoAlt: 'SaludNow logo',
      headline: 'A Partner For Growth',
      body: 'Abir helped us simplify a complex onboarding journey into a flow that our users now rave about. The collaboration was smooth and deeply insightful.',
      rating: 5,
      theme: 'sienna',
    },
    {
      id: 'liam-chan',
      author: 'Liam Chan',
      role: 'Founder, DBFEX',
      date: '2024-08-21T08:45:00Z',
      logo: 'logo.svg',
      logoAlt: 'PulseTrack logo',
      headline: 'Intuitive End-To-End Experience',
      body: 'We went from scattered ideas to a polished product vision. The strategy, research, and UI execution landed us our next round of funding.',
      rating: 5,
      theme: 'violet',
    },
  ],
  faqs: [
    {
      id: 'design-process',
      question: 'What is included in your design process?',
      answer: 'My process includes research, wireframing, visual design, prototyping, and usability testing — all tailored to your product goals.',
      open: true,
    },
    {
      id: 'startups',
      question: 'Do you work with startups?',
      answer: 'Absolutely — I help early-stage teams move from concept to MVP with strong UX foundations and fast, iterative delivery.',
      open: false,
    },
    {
      id: 'redesigns',
      question: 'Can you redesign existing apps?',
      answer: 'Yes. I run UX audits to identify usability issues, then redesign critical flows to lift engagement, retention, and conversion.',
      open: false,
    },
    {
      id: 'redesigns',
      question: 'Can you redesign existing apps?',
      answer: 'Yes. I run UX audits to identify usability issues, then redesign critical flows to lift engagement, retention, and conversion.',
      open: false,
    },
  ],
  cta: {
    buttonText: 'SCHEDULE A CALL',
    buttonHref: 'https://calendly.com/uixabir',
  },
};
